# Generated by Django 3.0.3 on 2020-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0003_hotelroomsdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingdata',
            name='phone',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
