# Generated by Django 3.0.3 on 2020-02-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0005_auto_20200222_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookingdata',
            name='email',
            field=models.EmailField(default='user@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='userbookingdata',
            name='fname',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AddField(
            model_name='userbookingdata',
            name='lname',
            field=models.CharField(default='title', max_length=30),
        ),
        migrations.AlterField(
            model_name='userbookingdata',
            name='phone',
            field=models.PositiveIntegerField(default='0'),
        ),
    ]
