# Generated by Django 3.0.3 on 2020-02-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0006_auto_20200222_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookingdata',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='userbookingdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='userbookingdata',
            name='fname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userbookingdata',
            name='lname',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userbookingdata',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
