# Generated by Django 3.0.3 on 2020-02-22 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0008_auto_20200222_2214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbookingdata',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userbookingdata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userbookingdata',
            name='last_name',
        ),
    ]
