# Generated by Django 3.0.3 on 2020-02-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0010_userbookingdata_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroomsdata',
            name='description',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotelroomsdata',
            name='image_path',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='hotelroomsdata',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
