# Generated by Django 3.0.3 on 2020-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0011_auto_20200224_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomsdata',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hotelroomsdata',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
