# Generated by Django 3.0.3 on 2020-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0012_auto_20200224_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroomsdata',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
